#!/usr/bin/env python3
"""
Generate phase lookup table for STM32 beamformer.

Creates a C source file with pre-computed sine/cosine values
optimized for embedded systems.

Usage:
    python3 generate_phase_lut.py --output src/phase_lut.c
"""

import math
import argparse


def generate_phase_lut(num_entries=4096, output_file=None):
    """
    Generate sine/cosine lookup table.

    Args:
        num_entries: Number of LUT entries (power of 2 recommended)
        output_file: Output C source file path
    """

    # Generate LUT
    sin_vals = []
    cos_vals = []

    for i in range(num_entries):
        angle = 2.0 * math.pi * i / num_entries
        sin_val = math.sin(angle)
        cos_val = math.cos(angle)

        # Convert to 16-bit fixed-point (Q15 format)
        sin_int = int(32767.0 * sin_val)
        cos_int = int(32767.0 * cos_val)

        # Clamp to range
        sin_int = max(-32768, min(32767, sin_int))
        cos_int = max(-32768, min(32767, cos_int))

        sin_vals.append(sin_int)
        cos_vals.append(cos_int)

    # Generate C code
    c_code = f"""/**
 * @file phase_lut.c
 * @brief Pre-computed sine/cosine lookup table
 *
 * Auto-generated by generate_phase_lut.py
 * Entries: {num_entries}
 * Format: Q15 fixed-point (16-bit signed)
 */

#include <stdint.h>

const int16_t sin_lut[{num_entries}] = {{
"""

    # Add sine values
    for i, val in enumerate(sin_vals):
        if i % 16 == 0:
            c_code += "\n    "
        c_code += f"{val:6d},"

    c_code += f"""
}};

const int16_t cos_lut[{num_entries}] = {{
"""

    # Add cosine values
    for i, val in enumerate(cos_vals):
        if i % 16 == 0:
            c_code += "\n    "
        c_code += f"{val:6d},"

    c_code += """
};
"""

    # Write to file
    if output_file:
        with open(output_file, 'w') as f:
            f.write(c_code)
        print(f"Generated {output_file}")
        print(f"  Entries: {num_entries}")
        print(f"  Size: ~{num_entries * 4} bytes (2× int16 arrays)")
    else:
        print(c_code)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Generate phase lookup table')
    parser.add_argument('--output', help='Output C file path')
    parser.add_argument('--entries', type=int, default=4096, help='Number of LUT entries')
    args = parser.parse_args()

    generate_phase_lut(num_entries=args.entries, output_file=args.output)
